### ISSUE TITLE
hijack fails missing constant Config

### ISSUE THREAD

**Issue by tpitale** [ileitch/hijack#18]
```
# hijack --debug 932
=> Hijacking.../opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/hijack-0.2.1/lib/hijack/gdb.rb:8:in `initialize': uninitialized constant Hijack::GDB::Config (NameError)
    from /opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/hijack-0.2.1/lib/hijack/payload.rb:9:in `new'
    from /opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/hijack-0.2.1/lib/hijack/payload.rb:9:in `inject'
    from /opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/hijack-0.2.1/lib/hijack/console.rb:10:in `initialize'
    from /opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/hijack-0.2.1/lib/hijack.rb:18:in `new'
    from /opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/hijack-0.2.1/lib/hijack.rb:18:in `start'
    from /opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/hijack-0.2.1/bin/hijack:27:in `<top (required)>'
    from /opt/rubies/ruby-2.2.2/bin/hijack:23:in `load'
    from /opt/rubies/ruby-2.2.2/bin/hijack:23:in `<main>'
```

**Comment by tahnok** [comment]
Seems like the version on rubygems is not the one in the latest version. After I install this git version manually this error went away (to be replaced by another error...)

**Comment by slieker-d** [comment]
Ouch. Over 2 years and no reply. I suppose this repo is no longer supported?
